### ISSUE TITLE
[BUG] Can't find player folder then crashes

### ISSUE THREAD

**Issue by bayron3** [gen3vra/starcheat-patched-bin#10]
**Describe the bug**
Starbound player folder does not exist.

You may need to run Starbound for the first time

Traceback (most recent call last):
  File "<string>", line 86, in <module>
  File "<string>", line 83, in main
  File "gui\mainwindow.py", line 229, in __init__
  File "gui\mainwindow.py", line 797, in open_file
  File "gui\openplayer.py", line 79, in __init__
  File "gui\openplayer.py", line 268, in auto_backup_player
AttributeError: 'list' object has no attribute 'keys'

**To Reproduce**
1. Run executable

**Expected behavior**
Application to work

**Screenshots**
![image](https://user-images.githubusercontent.com/104614069/198303618-076e5672-9a42-41e3-bc06-4a9f63ad479b.png)

**Environment (please MAKE SURE this is accurate):**
 - OS: windowwinv
 - OS Version: 21H2
 - Player species:
 - **Starcheat Version & Patch**: current

**Player File (if applicable)**
_If you've experienced a player issue, include a reproducible player file here_ [DELETE ME]

**Additional context/Clarification questions** _IF NEEDED_
_Add any other context about the problem here!_ [DELETE ME]

**Comment by gen3vra** [comment]
I honestly don't understand how to make this error message any clearer. are you saying that you DO have a player folder existing and it's not working? you can manually set a player path but it expects default steam install location

**Comment by bayron3** [comment]
Yes I have an existing folder. When I go to options it shows the correct path up to .../starbound. It then encounters the critical error and closes

**Comment by gen3vra** [comment]
If you already have a `starcheat.ini` file in your `%appdata%\starcheat` folder, edit the settings **assets_folder**, **player_folder** and **starbound_folder** to your preferred location

You can delete everything else in that folder besides the .ini file 

Here's an example (my starcheat.ini file on this device):
```
[starcheat]
check_updates = yes
mods_folder = C:\Program Files (x86)\Steam\SteamApps\common\Starbound\mods
disable_check_starbound_open = yes
assets_folder = C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets
player_folder = C:\Program Files (x86)\Steam\SteamApps\common\Starbound\storage\player
backup_folder = C:\Users\gen\AppData\Roaming\starcheat\backups
starbound_folder = C:\Program Files (x86)\Steam\SteamApps\common\Starbound
forceloadchar = no
assets_db = C:\Users\gen\AppData\Roaming\starcheat\assets.db
config_version = 15
pak_hash = 42061e724247a908d843d625a2627b65
```
