### ISSUE TITLE
[BUG] starcheat returns -1 on launch

### ISSUE THREAD

**Issue by main-tan** [gen3vra/starcheat-patched-bin#9]
**Describe the bug**
starcheat returned -1 after asking to rebuild the assets index

**To Reproduce**
1. Launch the executable.
2. Pressing either yes or no will give a critical error.
![image](https://user-images.githubusercontent.com/103846395/188286926-e99eddab-67eb-43a2-8276-a754425eeedf.png)

Pressing "yes":
![image](https://user-images.githubusercontent.com/103846395/188286973-d7bdfb4a-5545-4035-92da-71b427186232.png)
Traceback (most recent call last):
  File "<string>", line 86, in <module>
  File "<string>", line 83, in main
  File "gui\mainwindow.py", line 207, in __init__
  File "gui\utils.py", line 105, in check_index_valid
  File "gui\utils.py", line 54, in build_assets_db
  File "assets\core.py", line 53, in __init__
sqlite3.OperationalError: unable to open database file

Pressing "no":
![image](https://user-images.githubusercontent.com/103846395/188286995-d3680868-ccef-44fc-a8f0-34e7077ac6c7.png)
Traceback (most recent call last):
  File "<string>", line 86, in <module>
  File "<string>", line 83, in main
  File "gui\mainwindow.py", line 213, in __init__
  File "assets\core.py", line 53, in __init__
sqlite3.OperationalError: unable to open database file

**Environment:**
 - OS: Windows
 - OS Version: 20H2
 - **Starcheat Version & Patch**: 1.4 patch 4

**Additional context/Clarification questions** 
I have used older versions of starcheat on this pc before.
Starcheat executable is on drive D, as well as the game itself.
I tried unpacking the game assets but that didn't help.
I have steam workshop mods installed.
I have python installed.

**Comment by gen3vra** [comment]
If you haven't already found this link or figured it out:
https://wiki.starcheat.net/index.php/Main/Help

Delete the old Starcheat database and config files and let it rebuild
You can find in Windows:
C:\Users\\[username]\AppData\Roaming\starcheat
